### ISSUE TITLE
GPU Branch 4k / 8k ?

### ISSUE THREAD

**Issue by earsneyes** [kochd/electricsheep-hd-client#13]
Hi there,

i want to upscale the flock and wanted to ask if it might be possible to make the GPU branch render 4k or even 8k since it is rendering 50 times faster from the feels ?

Cheers
Linus

**Comment by kochd** [comment]
Hi Linus.

I'll have to investigate what that means regarding disk space on the server. I'll probably fire up a new gpu branch on Friday to see what happens.

If the server can not hold enough flocks before running out of space we'll need a bigger server for that.

**Comment by earsneyes** [comment]
sounds great! I am willing to help whatever is needed to make this happen 👍

**Comment by kochd** [comment]
The GPU branch has to be considered broken right now. No renders in it so i did not notice till now. I started using it and hit a ton of bugs.

**Comment by earsneyes** [comment]
Okay. I did try to render for GPU branch but as you say it did not work the past few days which is sad. Let me know if interest rises and if i can help debugging or suchalike. thanks for your affords!

**Comment by kochd** [comment]
@earsneyes @GeorgeHahn 
You could review the [draft release](https://github.com/kochd/electricsheep-hd-client/releases/download/untagged-1e1fd9e5273cea59b90b/Electric.Sheep.HD.Installer.exe) on Windows. I have no hardware running windows.

**Comment by kochd** [comment]
Okay maybe the access to drafts is restricted to me only. I published it [here](https://github.com/kochd/electricsheep-hd-client/releases/download/20180519/Electric.Sheep.HD.Installer.exe)

**Comment by kochd** [comment]
Wohoo avast is reviewing my software

**Comment by kochd** [comment]
@earsneyes gpu rendering should be working this client if you have hardware that works with fractorium if you want to test

**Comment by earsneyes** [comment]
![es-hd-client_1030gpu](https://user-images.githubusercontent.com/875876/40272870-4dce4972-5bb5-11e8-9e2c-a03600160f43.png)

I dont know if its a problem with my hardware at home (nvidia 1030) so i will try at work probably tomorrow!

**Comment by kochd** [comment]
Yeah seams like a fractorium problem.

Am 19. Mai 2018 22:39:13 MESZ schrieb Linus <notifications@github.com>:
>
>![es-hd-client_1030gpu](https://user-images.githubusercontent.com/875876/40272870-4dce4972-5bb5-11e8-9e2c-a03600160f43.png)
>
>I dont know if its a problem with my hardware at home (nvidia 1030) so
>i will try at work probably tomorrow!
>
>-- 
>You are receiving this because you modified the open/close state.
>Reply to this email directly or view it on GitHub:
>https://github.com/kochd/electricsheep-hd-client/issues/13#issuecomment-390431204

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by earsneyes** [comment]
I am not sure what broke since it worked before. more testing needed i guess :)

**Comment by earsneyes** [comment]
I did a fresh fractorium install and it works now until it tries to upload the frame.
![eshd_fractorium_upload](https://user-images.githubusercontent.com/875876/40276432-1037ba6c-5c0a-11e8-8335-9988bd5b208f.PNG)

**Comment by kochd** [comment]
That can be fixed server side. The server fail to use the same validation techniques that worked on linux for some reason. Just let i run and i will fix it.

Looks like fractorium behaves differently on different platforms.

**Comment by earsneyes** [comment]
With my nvidia 1030 each frame (1080p) takes around 10 seconds. Image quality seems good

![0547](https://user-images.githubusercontent.com/875876/40276685-c40c759a-5c10-11e8-8102-2e90e97be389.jpg)

**Comment by earsneyes** [comment]
ok great. i will need to stop by the office and turn on the client there since my card at home is passive cooled and will get to hot i fear. thanks for your help, much appreciated!

**Comment by kochd** [comment]
There is a chance that i already fixed it. By the way do you have to use --insecure ? That shouldn't be necessary.

**Comment by earsneyes** [comment]
Uploading works now and it works without --insecure. i tried that option while testing around some time ago.  i will let it run now and look later again when there are a few more frames rendered.

**Comment by earsneyes** [comment]
Great stuff! I will look at the 4k frames in the evening. How about setting up an 'archive' server for storage? I have a server and i am considering moving to a bigger one (2TB HDs) anyways.

**Comment by earsneyes** [comment]
The 4k sheeps are looking stunning on a 4k TV :)
Now I just need to get into designing new sheeps and try them by uploading a few.

 Thanks for the work you putting in!

Another thing I found is that the webpage sometimes blocks my requests. 

![es-hd_403](https://user-images.githubusercontent.com/875876/40361772-be810a3a-5dca-11e8-9af0-63a6be41f7e4.png)

Any Idea why that is ?

**Comment by kochd** [comment]
There is a request limit to prevent someone from flooding the server with requests. I raised the limit a bit. Just report back if you still have issues.
If you could provide storage space that would be great! If you could provide a NFS export the server could use it as its productive storage for frames and sequences.

**Comment by earsneyes** [comment]
Thanks! My machine in the office has a bigger GPU so it still gets blocked. At least if I browse the webpage additionally. 
I will have a look and compare offers to get my server upgraded. might take a week or so.

**Comment by kochd** [comment]
Yes. If they are in in a different branch they will be fighting about the content in the _.active-season_ file. That file is read by _play_ to determine which branch to play. That's the only weirdness to expect.

**Comment by earsneyes** [comment]
Ok great, will do that. 
How about selecting a specific gpu ? I think embveranimate supports a '--device_ switch :)
I have to work here and there in between and while opening After Effects it did crash the client here.

**Comment by kochd** [comment]
I found a bug on the website that only affected chrome users that caused their browsers to hammer on the /status route as fast as they could. That should have caused your problems with the server blocking you. Fixed

**Comment by earsneyes** [comment]
Hah :) I was wondering already why chrome. It was kind of strange to find this because Chrome is my only browser connected directly to the net via my ISP and not through vpn. Good job!

**Comment by kochd** [comment]
electricsheep.244.00003.00949_electricsheep.244.00003.00949 Frame 360:
![00360](https://user-images.githubusercontent.com/1825660/40453451-8561ecc6-5ee5-11e8-90d9-7e391fb34f0f.jpg)


electricsheep.244.00003.00949_electricsheep.244.00004.01632 Frame 361:
![00361](https://user-images.githubusercontent.com/1825660/40453425-69a3dd0a-5ee5-11e8-9a10-2428c2ee8915.jpg)

electricsheep.244.00003.00949_electricsheep.244.00004.01632 Frame 362:
![00362](https://user-images.githubusercontent.com/1825660/40453435-71c55efa-5ee5-11e8-99f8-0bf1c851f9bf.jpg)

All frames by @earsneyes probably a fractorium bug

**Comment by GeorgeHahn** [comment]
Could you attach the genome as well?

Thanks,
George

Sent from Outlook for Android

________________________________

**Comment by kochd** [comment]
https://sheeps.triple6.org/G244_W3840_H2160_Q1024_KY38402AGPU/animated_genomes/electricsheep.244.00003.00949_electricsheep.244.00003.00949.flame.gz
https://sheeps.triple6.org/G244_W3840_H2160_Q1024_KY38402AGPU/animated_genomes/electricsheep.244.00003.00949_electricsheep.244.00004.01632.flame.gz

**Comment by earsneyes** [comment]
What can i do to debug this or help resolve it ? What was the ip address from that submission ? (I have two machines running two different cards / machines)

Thanks!

**Comment by kochd** [comment]
<pre>
emberanimate --in=electricsheep.244.00003.00949_electricsheep.244.00004.01632.flame --format=jpg --opencl --sp --supersample=2 --begin 359 --end 360 --isaac_seed=fractorium 
</pre>

You'll get a 0360.jpg 

I rendered it and it was fine. 
01:00.0 VGA compatible controller: NVIDIA Corporation GF108M [NVS 5400M] (rev ff)

**Comment by earsneyes** [comment]
I rendered the frame with both machines and even with two cards together (1070 & 1050Ti) and it came out fine as well. 
Maybe it was the frame rendered when i was working while rendering or when the client crashed. Maybe the machine didnt like running GPU&CPU renderer at the same time. 
I will test a few more scenarios.

**Comment by kochd** [comment]
<pre>
emberanimate --in=electricsheep.244.00003.00949_electricsheep.244.00004.01632.flame --format=jpg --opencl --sp --supersample=2 --begin 359 --end 365 --isaac_seed=fractorium 
</pre>
Actually the server asked you to render 4 frames from 360 ahead. I don't think it makes any difference but this is what actually got executed on your machine. Also it happened two time as is let you render it again. Cant tell which machine of yours send what.

**Comment by earsneyes** [comment]
Ok thanks! I rendered the full 360 frames without a single glitch at home (gtx 1030). 
At work i could reproduce it twice with both cards seperatly (1070 & 1050 Ti) as well as using both.
I will dig deeper.

**Comment by kochd** [comment]
@earsneyes i would recommend to update the nvidia drivers and then check if that solves the glitches.

**Comment by earsneyes** [comment]
That was what i was thinking as well but it didnt solve it. I tried fresh fractorium & client install as well, no success yet. 
more tests to come.

**Comment by earsneyes** [comment]
I have encountered another problem "failed to allocate memory", do you have an idea ?
This keeps happening on both my machines and so the client only renders about half an hour to an hour at most.

![es-hd_nomemoryerror](https://user-images.githubusercontent.com/875876/40710575-4b61ec2e-63f9-11e8-83d9-d3b5996650a4.PNG)

Any idea ?

**Comment by kochd** [comment]
good catch. Should be fixed now. Thanks for reporting @earsneyes

**Comment by earsneyes** [comment]
Thanks for your fix! Unfortunately it still occurs here and there.
![es-hd_nomemoryerror2](https://user-images.githubusercontent.com/875876/40823882-51720ac0-6572-11e8-9590-73ef89a953e0.PNG)

**Comment by kochd** [comment]
Too bad that just moved the problem to a different spot.
@earsneyes i just pushed this to master 8d78e6008c8c2f4641aacae5fd98258c97b5650d

Could you replace your daemon with this version?:
https://raw.githubusercontent.com/kochd/electricsheep-hd-client/master/daemon

**Comment by earsneyes** [comment]
sure. thanks for the quick fix!

**Comment by earsneyes** [comment]
Movies are coming over truncated unfortunatly now.
![eshd_truncated](https://user-images.githubusercontent.com/875876/40845696-cbb5c322-65b7-11e8-9459-a264470f10ca.PNG)

**Comment by kochd** [comment]
As it matches the expected duration of 15,0s there is no way it could be trucated. We con cat 360 frames at 24 fps which leads to a duration of 15,0s

**Comment by earsneyes** [comment]
Somehow the last few files didnt want to play for me at all, now they play except for the last three that are larger than usual (>500 MB).

**Comment by kochd** [comment]
I was tinkering around with the rendering process these days. You can delete the ones that are broken to download them again.

**Comment by kochd** [comment]
@earsneyes https://github.com/kochd/electricsheep-hd-client/commit/20a426c5ce10c13d0160ac1d625c04cbd5da6af4 There was indeed corruption for windows users introduced by the chunked download.

**Comment by earsneyes** [comment]
Hey there, i was quite busy the last weeks but I am back now an try to make this happen after the vacation starting next week. hope everything is going well!

**Comment by kochd** [comment]
I am closing this issue as GPU branch seams to be rock solid in 4k now.

**Comment by earsneyes** [comment]
sorry it took me so long. But i am hungry for 4k sheeps again :)

Have the new machine that can store a few sheeps / frames now.
Can you maybe assist me with setting things up ?

Thanks!

**Comment by kochd** [comment]
Hey Linus,

I dont think we are going to use an external storage. I expanded on the server and the current configuration should be able to hold up to 500 GPU rendered sequences before it needs to make free space by deleting the old one.

I was also messing around with some really nerdy ideas where no storage for archiving would be needed at all. We just load the space of to clients as the archive everything anyway. I'll writing a new enhancement "issue" about the design of this.

**Comment by kochd** [comment]
https://github.com/kochd/electricsheep-hd-client/issues/28 is a quick write down of what i have in mind. There are some long nights to spend coding between the concept and the implementation.

We also need a board on the site or something for general conversations :smile:

**Comment by earsneyes** [comment]
OK so i am going to spin my machine up for some redering :)

As forum / board software i suggest https://www.discourse.org/.
